specVersion: "0.0.1"
description: ""
repository: "https://github.com/onfinality-io/subql-starter"

schema: "./schema.graphql"

endpoint: "wss://rpc.polkadot.io"

dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 1
    mapping:
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler





